### ISSUE TITLE
How to import extra packages from Hackage

### ISSUE THREAD

**Issue by aherrmann** [FormationAI/hazel#48]
What is the intended mechanism for adding packages that are not in the Stackage snapshot from Hackage into a Hazel project?

Looking at the docstring on [`hazel_custom_package_hackage`](https://github.com/FormationAI/hazel/blob/925293994f88799ba550fd5cf3995104d1f2972c/hazel.bzl#L178) it sounds like the right tool:

> Generate a repo for a Haskell package fetched from Hackage.

However, `hazel_custom_package_hackage` and `hazel_custom_package_github` do not use `_cabal_haskell_repository` internally but instead refer to a dedicated per-package `BUILD` file that has to be present in the `hazel` repository. So, these functions don't work for arbitrary Hackage packages, but only those for which Hazel has builtin support.

On the other hand, we can manually extend the `packages` parameter to `hazel_repositories`. E.g.

```
load("//hazel:packages.bzl", "core_packages", "packages")
hazel_repositories(
  core_packages = core_packages,
  packages = packages + {
    "some-package": struct(
      version = "x.y.z.w",
      sha256 = "...",
    ),
  },
  ...
)
```

Unfortunately, this has to be done in a `.bzl` file because `struct` cannot be used in `WORKSPACE` (AFAIK), which makes this boilerplate heavy. Maybe `hazel_repositories` should have an additional parameter `extra_packages` that takes a `dict` of `dict`s to make this extensible in a `WORKSPACE` file?

cc @mrkkrp @nmattia

**Comment by thumphries** [comment]
> a dedicated per-package BUILD file that has to be present in the hazel repository. So, these functions don't work for arbitrary Hackage packages, but only those for which Hazel has builtin support.

This is not accurate, custom BUILD files just need to be placed in `third_party/haskell/BUILD.packagename` in your repository. I believe the relevant logic is [here](https://github.com/FormationAI/hazel/blob/925293994f88799ba550fd5cf3995104d1f2972c/hazel.bzl#L193).

**Comment by thumphries** [comment]
We should probably document this and/or have a few examples.

I'd be in favour of creating a common resource for custom build files, potentially tracking Stackage snapshots. We have a few dozen of them in our private tree.

**Comment by aherrmann** [comment]
> > a dedicated per-package BUILD file that has to be present in the hazel repository. So, these functions don't work for arbitrary Hackage packages, but only those for which Hazel has builtin support.
> 
> This is not accurate, custom BUILD files just need to be placed in `third_party/haskell/BUILD.packagename` in your repository. I believe the relevant logic is [here](https://github.com/FormationAI/hazel/blob/925293994f88799ba550fd5cf3995104d1f2972c/hazel.bzl#L193).

Ah, sorry, I misread that. Thanks for the pointer.

>I'd be in favour of creating a common resource for custom build files, potentially tracking Stackage snapshots. We have a few dozen of them in our private tree.

In what kind of cases is a custom `BUILD` file required? At least in the cases I've tried, just adding an item to `packages` worked out just fine.

**Comment by thumphries** [comment]
Most of our overrides fall into the following categories:
- Silencing warnings for packages that aren't `-Wall` clean
- Supporting cbits
- Supporting some cabal conditionals
- Anything requiring a custom Setup.hs

I didn't do any of this work so I'm not sure if cabal2bazel supports C sources at all or if we're overriding unusual cases. Same for default-extensions etc.

**Comment by judah** [comment]
Hazel (as well as cabal2bazel) automatically turns Cabal c-sources into a Bazel cc_library: https://github.com/FormationAI/hazel/blob/925293994f88799ba550fd5cf3995104d1f2972c/third_party/cabal2bazel/bzl/cabal_package.bzl#L288

Quite a few packages work automatically, but I recall we ran into some edge cases that it was easiest to work around with package overrides.

**Comment by thumphries** [comment]
Closing for now, feel free to reopen
