### ISSUE TITLE
Colliding workspace names on case-insensitive system

### ISSUE THREAD

**Issue by aherrmann** [FormationAI/hazel#52]
Hazel generates an external workspace for each of the packages provided in the `core_packages` and `packages` attributes to `hazel_repositiories`. E.g. `haskell_vector` for `vector`. Hackage allows package names to only differ in case. E.g. `HSet` and `hset`. This will generate workspace names `haskell_HSet` and `haskell_hset`. On a case-insensitive system, in particular on Windows, Bazel will not distinguish these two workspace names, leading to errors like the following:

```
ERROR: C:/users/user/_bazel_user/glk6p2o5/external/ai_formation_hazel/hazel.bzl:172:3: Label '@haskell_HSet//:files' is duplicated in the 'files' attribute of rule 'all_hazel_packages'
```

## Temporary Workaround

Commenting out instances of such names in the generated `hazel/packages.bzl` file resolves that issue. (Of course that's just a work around)

## Proposed resolution

I've done some preliminary tests on Windows with the following approach and they show that it resolves this issue.

I propose to append case-sensitive information to the generated workspace names. To that end we can use the [`hash` function](https://docs.bazel.build/versions/master/skylark/lib/globals.html#hash) that Bazel offers, and append the hash of the package name to the generated workspace name. We can also lower case workspace names to ensure that other issues related to case insensitivity are also caught on Linux.

This would generate workspace names like the following
```
HSet -> haskell_hset_2227962
hset -> haskell_hset_3212026
SCalendar -> haskell_scalendar_191454385
scalendar -> haskell_scalendar__1877157711
```
(The double `_` occurs when the result of `hash` is a negative number)

Disadvantages:
- It makes it harder for users to predict the generated workspace names and query information about external dependencies. Maybe this can be resolved using `bazel query` or a package group.
- This assumes that there are no hash collisions between package names that only differ in case. (I haven't observed any so far) If collisions ever occur, the method could be further refined.

Let me know what you think of this approach and I'll be happy to create a PR.

**Comment by thumphries** [comment]
Bazel's `hash` seems very weak, but (as you say) collisions on packages that differ only by case seems fairly unlikely. I'd like to see a test of this before proceeding.

The unpredictable names are unfortunate. I can't think of a better way to do it though. They are not quite user-facing so this could be fine.

**Comment by aherrmann** [comment]
@thumphries Thanks! I've run the following test to see if Bazel's hash function produces collisions in relevant cases.

- Download Stackage LTS 12.4 resolver file
- Inflate the number of package names that only differ in case as follows.
    - For each package name, add 99 copies of the package name.
    - For each copy capitalize or lower case random letters in the package name.
    - Deduplicate the resulting list of randomly capitalized package names.
- Apply the proposed mechanism to make names case insensitive.
    I.e. given `<name>`, produce `<lower case name>-<hash of name>`.
- Deduplicate the resulting list of case insensitive names.
- Check that their number matches the number of unique randomly capitalized names.

(I've collected the steps into this [gist](https://gist.github.com/aherrmann/3fee352d1d5f82cb5c0ce18d597fd43d).)

This test showed that Bazel's hash is sufficient to disambiguate these names. With that result, I think it is safe to proceed.
