### ISSUE TITLE
linkstatic = True causes Hazel builds to fail

### ISSUE THREAD

**Issue by aherrmann** [FormationAI/hazel#64]
Hazel builds fail with linker errors if `linkstatic` is set to `True`, which is the default in rules_haskell. Currently, Hazel works around this by setting `linkstatic = False`. However, for various reasons it would be preferable to use static linking, or at least have it available. E.g. startup speed of executables, MacOS MACH-O header size limit, Haskell profiling (AFAIK currently only available with static linking in rules_haskell).

It is unclear to me whether the issue lies in rules_haskell or Hazel. I was under the impression that it is a known limitation in rules_haskell. However, I was unable to reproduce the same kind of linker errors  rules_haskell alone.

cc @guibou

---

To reproduce:
- Check out the `test-static-linking` branch on the following Hazel clone: https://github.com/DACH-NY/hazel (7904fad762580e4842501b2f0b8fb29e37cc6586 at the time of writing)
- Run the tests as follows:

    ```
    nix-shell --pure path/to/rules_haskell/shell.nix --run 'bazel test //test/vector-test'
    ```

    Assuming a checkout of rules_haskell at commit d5203b8273fa53d68341e8bf0dc7cb8f14ebbf6c.

 - Observe linker errors of the following form

    ```
    bazel-out/k8-fastbuild/bin/external/haskell_primitive__1834808089/libHSexternalZShaskellZUprimitiveZUZU1834808089ZSprimitive.a(Primitive.o):s2YJ_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziCont_zdfMonadTransContT_closure'
    bazel-out/k8-fastbuild/bin/external/haskell_primitive__1834808089/libHSexternalZShaskellZUprimitiveZUZU1834808089ZSprimitive.a(Primitive.o):externalZZShaskellZZUprimitiveZZUZZU1834808089ZZSprimitive_ControlziMonadziPrimitive_zdfPrimMonadContT_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziCont_zdfMonadContT_closure'
    bazel-out/k8-fastbuild/bin/external/haskell_primitive__1834808089/libHSexternalZShaskellZUprimitiveZUZU1834808089ZSprimitive.a(Primitive.o):s2YP_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziIdentity_zdfMonadTransIdentityT_closure'
    ```

**Comment by guibou** [comment]
Thank you, that's a smaller repro than the one I had to work. I'm looking at it.

**Comment by guibou** [comment]
Good catch. Thank you. This helps.

**Comment by aherrmann** [comment]
Yes, this is fixed upstream. I forgot to close here. Thanks for the reminder.
