### ISSUE TITLE
Instructions in the README are broken, can't find any working examples

### ISSUE THREAD

**Issue by per-gron** [FormationAI/hazel#74]
I've been trying to use Hazel this past day and a bit yesterday, and have unfortunately so far not been successful. I would submit a PR to try to fix this, but I really don't understand what the right way of using this repo is.

There is [rules_haskell_examples](https://github.com/tweag/rules_haskell_examples), but it's old and does not work with recent Bazel (it uses `http_archive` without importing it, and depends on and old `rules_haskell` that does the same). Maybe I should just downgrade Bazel and use old versions of everything...

It would be helpful if the `README.md` instructions contained the `load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")` line.

`README.md` has code to add to `WORKSPACE` that has syntax errors in it around `HAZEL_SHA`: It's missing `"`s.

The version of Hazel that the `README.md` instructions point to using (via git hash) has a `hazel_repositories` rule(?) that does not accept the `core_packages` attribute that the example code has so it doesn't work.

Issue #53 makes it, as far as I can tell at least, impossible to use `rules_haskell`'s `haskell_register_toolchains` since that does not set up a `@ghc` workspace.

Nevertheless, I still managed to make things build by importing `@ghc` with `nixpkgs_package` instead of using `haskell_register_toolchains`. However, I get `error while loading shared libraries: libHSrts_thr-ghc8.2.2.so` runtime errors which I don't know how to fix. That file is present somewhere in `/nix` but I don't know how to point my binaries to it. I've found that there is a `:threaded-rts` target in `BUILD.ghc` that tries to work around it but it doesn't seem to work.

What can I do to make this work? Is there some other repo like [rules_haskell_examples](https://github.com/tweag/rules_haskell_examples) that works with recent Bazel versions that I can look at?

**Comment by mjrussell** [comment]
@per-gron I recently got things working for me. I've just uploaded a gist with my scaffolding here - https://gist.github.com/mjrussell/6ff128bf13a1aba34e1fe7fa4957a376.

Let me know if that works for you or you run into any issues. I probably need to flesh out the instructions a bit more but hopefully it's a useful starting point. I can try to convert this to an example repo at some point

**Comment by thumphries** [comment]
If you make your repository public we can help you with it

Hazel itself uses hazel to build dependencies, so our [WORKSPACE](https://github.com/FormationAI/hazel/blob/master/WORKSPACE) is perhaps the best public example of usage. Agree we should have some more examples

**Comment by per-gron** [comment]
Thanks @thumphries and @mjrussell for the pointers. I will probably be able to get it working from that.

I think this ticket was closed prematurely though, it's not just about me failing to use it on my own project, it's also about the fact that the instructions have code with obvious syntax errors, and even when the syntax errors are not fixed they don't work. This makes it quite difficult for anyone to start using Hazel. At the very least the README instructions could be replaced with "We don't currently have detailed instructions, please refer to how this repository is set up." That would have been enough for me to get going.
